Add Starname (IOV)
trustwallet/wallet-core pull request #1123
Opened 2020-09-30 17:46 UTC by davepuchyr

## Description

Add IOV (based on BandChain). The iov-mainnet-2 chain is built on cosmos-sdk, just like BandChain.

## Testing instructions

Test in the same manner as BandChain was tested.

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [ ] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

2020-09-30 23:50 UTC, catenocrypt requested changes

2020-09-30 23:50 UTC, catenocrypt commented on docs/coins.md
> +| 234     | IOV              | IOV    | <img src="https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/iov/info/logo.png" width="32" />          | <https://starname.me>         |
The URL is 404.  Please add chain logo.png and info.json to assets repository.

2020-09-30 23:50 UTC, catenocrypt commented on tests/IOV/TWCoinTypeTests.cpp
> +auto symbol = WRAPS(TWCoinTypeConfigurationGetSymbol(TWCoinTypeIOV));
Proper fomatting (indenting) please.

2020-09-30 23:52 UTC, catenocrypt commented
Looks good.
Please also create a PR for https://github.com/trustwallet/assets repo, to add https://github.com/trustwallet/assets/tree/master/blockchains/iov/info, with logo.png and info.json (look at iotex for example).

2020-10-01 08:05 UTC, davepuchyr commented on tests/IOV/TWCoinTypeTests.cpp
> +auto symbol = WRAPS(TWCoinTypeConfigurationGetSymbol(TWCoinTypeIOV));
Done via https://github.com/trustwallet/wallet-core/pull/1123/commits/3248d526f21884323bcb11cf0957a6ff9dd675f5.

2020-10-01 11:11 UTC, catenocrypt commented
Upon more careful review, it looks like Starname does not meet our blockchain inclusion criteria.  Closing, sorry.

https://developer.trustwallet.com/wallet-core/newblockchain

2020-10-01 11:11 UTC, closed without merging