Rename BNB chain names
trustwallet/wallet-core pull request #2025
Opened 2022-02-16 14:43 UTC by catenocrypt

## Description
Rename BNB chain names: 'BNB Beacon Chain' and 'BNB Smart Chain'. Fixes #2023 .

## Testing instructions

Unit tests.

## Types of changes

* Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [x] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

2022-02-16 22:22 UTC, hewigovens approved these changes

2022-02-18 04:25 UTC, vikmeup commented on tests/BinanceSmartChain/TWCoinTypeTests.cpp
> +    assertStringsEqual(name, "BNB Smart Chain");
```suggestion
    assertStringsEqual(name, "Smart Chain");
```

2022-02-18 04:26 UTC, vikmeup commented on tests/Binance/TWCoinTypeTests.cpp
> +    assertStringsEqual(name, "BNB Beacon Chain");
I would keep as is for now. otherwise it's confusing in UI

2022-02-18 04:26 UTC, vikmeup requested changes
I think we should be ok to keep as is

2022-02-18 04:36 UTC, hewigovens commented
Only need to update icon then?

2022-02-22 07:45 UTC, hewigovens commented
let's close this for now

2022-02-22 07:45 UTC, closed without merging