Add Platon Support
trustwallet/wallet-core pull request #2150
Opened 2022-04-18 10:47 UTC by benben2019

## Description

Add Platon support.

## Testing instructions

Test in the same manager as KCC was tested.

## Types of changes

New feature (non-breaking change which adds functionality) 

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain
- [ ] If there is a related Issue, mention it in the description (e.g. Fixes #<issue_number> ).

2022-04-19 09:16 UTC, catenocrypt requested changes

2022-04-20 04:23 UTC, benben2019 commented on src/proto/Platon.proto
> +message TransferMessage {
Platon.proto is no need. just reused Eth code.

2022-04-20 04:24 UTC, benben2019 commented on swift/Podfile.lock
> +COCOAPODS: 1.11.3
Sorry about this.

2022-04-20 04:25 UTC, benben2019 commented on docs/registry.md
> +| 486     | Platon           | LAT    | <img src="https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/platon/info/logo.png" width="32" />       | <https://www.platon.network/en> |
OK, I submitted a PR: https://github.com/trustwallet/assets/pull/19918

2022-04-25 23:08 UTC, hewigovens commented
Thanks for your interests, we will consider adding it later

2022-04-25 23:08 UTC, closed without merging

2022-05-18 07:14 UTC, benben2019 commented
> Thanks for your interests, we will consider adding it later

Now we decide to pay the fee, would you please reopen this PR?  Thanks! 
And the logo & info PR #https://github.com/trustwallet/assets/pull/19918