Add TWBase64 interface exposing Base64 implementation
trustwallet/wallet-core pull request #2390
Opened 2022-07-19 17:10 UTC by miloserdow

Similarly to https://github.com/trustwallet/wallet-core/blob/master/include/TrustWalletCore/TWBase32.h, expose Base64 implementation from core library to Swift/Kotlin, issue: #2369

## Description

## How to test

* Run core tests
* Run Android tests
* Run iOS tests
* Run WASM tests

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Create pull request as draft initially, unless its complete.
- [ ] Add core tests
- [ ] Add Android tests
- [ ] Add Swift tests
- [ ] Add WASM tests
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

2022-07-20 06:43 UTC, Milerius commented on tests/interface/TWBase64Tests.cpp
> +}
New end of lines, If you use CLion, in editor options you can add a new lines at end of files on save.

2022-07-20 06:43 UTC, Milerius commented on include/TrustWalletCore/TWBase64.h
> +TW_EXTERN_C_END
Same remarks

2022-07-20 16:04 UTC, catenocrypt reviewed
Looks good so far.  Kotlin/Swift tests could be also added, isn't it?

2022-07-25 12:47 UTC, hewigovens commented
@miloserdow what's the status of this one? do you need help to add mobile tests?

2022-07-25 20:15 UTC, miloserdow commented
> @miloserdow what's the status of this one? do you need help to add mobile tests?

No, I'm fine, I'll wrap it up soon. Was focusing on something else

2022-07-26 15:55 UTC, Milerius requested changes

2022-07-26 15:55 UTC, Milerius commented on tests/interface/TWBase64Tests.cpp
> +s
Spurious letter

2022-07-26 17:21 UTC, miloserdow commented
Not sure what's wrong with this wasm test

2022-07-26 21:55 UTC, hewigovens commented
Will take a look, it's passed locally? might be some difference between Linux / macOS

2022-07-27 09:51 UTC, miloserdow commented
So there was the problem with wasm not being able to catch exceptions in C++ code properly which was causing the error. I changed our Base64 implementation and it should pass now.

2022-07-27 10:19 UTC, catenocrypt approved these changes
+1!

2022-07-27 10:21 UTC, Milerius approved these changes

2022-07-27 11:54 UTC, hewigovens approved these changes
nice work 🚀

2022-07-27 17:51 UTC, merged