[PrivateKey]: add new C interface to get public key with cointype
trustwallet/wallet-core pull request #2661
Opened 2022-10-18 07:30 UTC by Milerius

## Description

fix #2656

## How to test

run c++ unit tests

## Checklist

- [x] Create pull request as draft initially, unless its complete.
- [x] Add tests to cover changes as needed.
- [x] Update documentation as needed.
- [x] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [x] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

2022-10-18 08:42 UTC, catenocrypt requested changes
I think the method to get public key type from a coin type should be in PrivateKey, and then there is no dependency issues.

2022-10-18 08:45 UTC, Milerius commented
> I think the method to get public key type from a coin type should be in PrivateKey, and then there is no dependency issues.

That's the case: https://github.com/trustwallet/wallet-core/pull/2661/files#diff-7a19dd450838cf7c739919131c63557db3b685641ea91469fd00e287d4f564aeR73

2022-10-20 00:03 UTC, hewigovens approved these changes
One more Kotlin test would be nice

2022-10-20 07:23 UTC, catenocrypt approved these changes
I suggest to add these two pathways in a single test:

- A1: get pubkey for coin type (e.g. Eth)

- B1: get pubkey type for coin type
- B2: get pubkey for obtained pubkey type

Result should be the same.

2022-10-20 07:23 UTC, catenocrypt commented on include/TrustWalletCore/TWCoinType.h
> +
```suggestion
```

This can be removed, not used

2022-10-20 07:50 UTC, hewigovens approved these changes

2022-10-20 07:58 UTC, Milerius commented
> I suggest to add these two pathways in a single test:
> 
> * A1: get pubkey for coin type (e.g. Eth)
> * B1: get pubkey type for coin type
> * B2: get pubkey for obtained pubkey type
> 
> Result should be the same.

Should we extend the C interface to have a `TWPrivateKeyGetPublicKeyByType(enum TWPublicKeyType pubkeyType)` or only write the second path in C++?

2022-10-20 12:25 UTC, hewigovens approved these changes

2022-10-21 11:18 UTC, catenocrypt approved these changes

2022-10-21 12:39 UTC, miloserdow approved these changes

2022-10-21 16:02 UTC, merged