[Barz] Format signature API changes
trustwallet/wallet-core pull request #3241
Opened 2023-06-19 20:30 UTC by rsrbk

A better way to build clientDataJSONPre and clientDataJSONPost would be to accept the whole clientDataJSON and split it in two parts (while avoiding challenge=userOpHash), rather than have a hardcoded JSON inside our implementation.

2023-06-19 20:31 UTC, rsrbk commented on src/Ethereum/Barz.cpp
> +    challengeBase64.pop_back();
Is there a better way to remove the last "=" from Base64 encoded result?

2023-06-20 08:35 UTC, satoshiotomakan requested changes

2023-06-20 10:33 UTC, rsrbk commented on src/Ethereum/Barz.cpp
> +    challengeBase64.pop_back();
Yes, "=" is always omitted in webauthn: https://w3c.github.io/webauthn/#base64url-encoding
Thanks, I'll update the code!

2023-06-20 10:43 UTC, satoshiotomakan approved these changes
Awesome!

2023-06-20 11:58 UTC, Milerius approved these changes

2023-06-20 11:59 UTC, merged