feat: Canto EVM
trustwallet/wallet-core pull request #3499
Opened 2023-10-23 19:55 UTC by Amurmurmur

## Description

Add support for Canto EVM-compatible chain

## How to test

## Types of changes

## Checklist

- [ ] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

2023-10-30 12:13 UTC, satoshiotomakan requested changes
Thank you for opening the PR! I have only one note

2023-10-30 12:13 UTC, satoshiotomakan commented on swift/Podfile.lock
> +COCOAPODS: 1.13.0
Could you please revert this file?

2023-10-31 10:09 UTC, satoshiotomakan commented
Hi @Amurmurmur, could you please fix the merge conflicts?

2023-11-02 14:04 UTC, Milerius commented
Not merging because of: https://twitter.com/CantoPublic/status/1703809950290718871

2023-11-02 14:04 UTC, closed without merging