[PoC/Bitcoin/Utxo] Correclty Consider Fees for UTXO selectionelection
trustwallet/wallet-core pull request #3667
Opened 2024-01-17 20:35 UTC by lamafab

See https://github.com/trustwallet/wallet-core/pull/3666 for more context.

2024-01-19 07:53 UTC, satoshiotomakan requested changes
The estimation algorithm looks promising and quite clear to understand!
I have only one major change request, please consider it t be changed or discussed

2024-01-19 07:53 UTC, satoshiotomakan commented on rust/tw_bitcoin/tests/free_estimate.rs
> +#[ignore]
Can we enable the tests?

2024-01-22 16:22 UTC, Milerius approved these changes

2024-01-22 17:02 UTC, satoshiotomakan approved these changes

2024-01-22 17:03 UTC, merged