feat: add solana token 2022 support
trustwallet/wallet-core pull request #3968
Opened 2024-08-02 14:54 UTC by weixuefeng

fix: https://github.com/trustwallet/wallet-core/discussions/3934

2024-08-05 08:32 UTC, satoshiotomakan requested changes
Hi @weixuefeng, thank you for opening the PR.
Please also fix rustfmt and(?) clippy warnings

2024-08-05 08:32 UTC, satoshiotomakan commented on rust/chains/tw_solana/src/modules/compiled_keys.rs
> +        writable_signer_keys.sort();
Could you please revert the keys sorting? Even though, they're sorted in official Solana lib, but in WalletCore I disabled it explicitly to save backward compatibility to have the same transaction signature after the Rust transition.
Please note that the keys are not required to be sorted to be valid transaction

2024-08-05 08:32 UTC, satoshiotomakan commented on rust/chains/tw_solana/src/modules/compiled_keys.rs
> +        readonly_signer_keys.sort();
Same here

2024-08-05 08:32 UTC, satoshiotomakan commented on rust/chains/tw_solana/src/modules/compiled_keys.rs
> +        writable_non_signer_keys.sort();
Same here

2024-08-05 08:32 UTC, satoshiotomakan commented on rust/tw_any_coin/tests/chains/solana/solana_sign.rs
>          ..Proto::CreateAndTransferToken::default()
You can ignore `is_token_2022` field here as `..Proto::CreateAndTransferToken::default()` leaves it default (false) value. Same in other places

2024-08-05 11:22 UTC, satoshiotomakan commented
@weixuefeng I can push the fix commit if you're ok, just let me know

2024-08-06 02:45 UTC, weixuefeng commented
> @weixuefeng I can push the fix commit if you're ok, just let me know

updated. @satoshiotomakan

2024-08-06 10:47 UTC, satoshiotomakan commented
I can't push fix commits, so please run `cargo fmt` at the `rust` directory. Please also make sure all tests pass, and `cargo clippy` do not produce warnings

2024-08-09 15:51 UTC, satoshiotomakan commented
Hi @weixuefeng, did you have a chance to fix the formatting by running `cargo fmt` and `cargo clippy`?

2024-08-10 05:47 UTC, weixuefeng commented
> Hi @weixuefeng, did you have a chance to fix the formatting by running `cargo fmt` and `cargo clippy`?

only fix cargo fmt and cargo clippy. but rust test have some error. i don't know how can i generate signature. and the preImageHash for transaction is different. i have not resolve it.

2024-08-12 08:06 UTC, satoshiotomakan commented
Hi @weixuefeng, do you mean you can fix `test_solana_sign_create_and_transfer_token_2022` and `test_solana_sign_transfer_token_2022` tests after removing the keys reordering? You can regenerate and rebroadcast the transactions.
Other tests should pass since there is no breaking changes anymore if `is_token_2022: false`

2024-08-12 13:36 UTC, weixuefeng commented
> Hi @weixuefeng, do you mean you can fix `test_solana_sign_create_and_transfer_token_2022` and `test_solana_sign_transfer_token_2022` tests after removing the keys reordering? You can regenerate and rebroadcast the transactions. Other tests should pass since there is no breaking changes anymore if `is_token_2022: false`

yes. removing the keys reordering can broadcast success on devnet.

but there have some problem. i guess the protocol buffer content had change (because add field `is_token_2022`). so the `preimage_output.data.to_hex()` had changed.  and what is the `signature1` and `signature2` ? how can i generate it. or the   
`output.encoded` test had failed maybe the signature is wrong?
@satoshiotomakan

2024-08-12 22:37 UTC, 0xh3rman commented
@weixuefeng @satoshiotomakan Maybe it's better to create an enum for token standard? not `bool` type or we can pass the token program as an argument in protobuf model cause it seems compatible with Token Program

2024-08-13 09:09 UTC, weixuefeng commented
> @weixuefeng @satoshiotomakan Maybe it's better to create an enum for token standard? not `bool` type or we can pass the token program as an argument in protobuf model cause it seems compatible with Token Program

I think tokenProgramId is very slow to update, so I stick with bool value. How about refactoring if there are more programId in the future?
@0xh3rman

2024-08-13 09:19 UTC, weixuefeng commented
Please check update. @satoshiotomakan

2024-08-14 14:15 UTC, satoshiotomakan requested changes
Hi @weixuefeng, I agree with @0xh3rman, could you please add an enum in Solana.proto. Please make a few small changes as well

2024-08-14 14:15 UTC, satoshiotomakan commented on rust/chains/tw_solana/src/modules/instruction_builder/token_instruction.rs
> +        is_token_2022: bool,
Please take `token_program_id: SolanaAddress` instead.

2024-08-14 14:15 UTC, satoshiotomakan commented on rust/chains/tw_solana/src/modules/instruction_builder/token_instruction.rs
> +        is_token_2022: bool,
Same `token_program_id: SolanaAddress` here

2024-08-14 16:25 UTC, weixuefeng commented on rust/chains/tw_solana/src/modules/instruction_builder/token_instruction.rs
> +        is_token_2022: bool,
done

2024-08-14 22:42 UTC, 0xh3rman reviewed
LGTM

2024-08-14 22:42 UTC, 0xh3rman commented on rust/chains/tw_solana/src/modules/message_builder.rs
> +
```suggestion        
```

2024-08-15 09:37 UTC, satoshiotomakan commented
Hi @weixuefeng, could you please format the code using `cargo fmt`? Please also make sure `cargo clippy` doesn't produce warnings, and all tests pass. I'm sure there is no breaking changes, so `test_solana_compile_create_and_transfer_token_with_external_fee_payer` should also pass without problems

2024-08-16 08:55 UTC, satoshiotomakan approved these changes
LGTM

2024-08-16 13:02 UTC, merged